option to pass "FIRSTDAY" argument to "date -d"

diff --git a/scripts/check_outp b/scripts/check_outp
--- a/scripts/check_outp
+++ b/scripts/check_outp
@@ -1,6 +1,6 @@
 #! /usr/bin/env bash
 
-# $Header: /u/gcmpack/mitgcm.org/scripts/check_outp,v 1.3 2008/09/09 18:09:37 jmc Exp $
+# $Header: /u/gcmpack/mitgcm.org/scripts/check_outp,v 1.4 2008/09/11 16:10:00 jmc Exp $
 #
 #  The purpose of this script is to compare
 #  the latest output with the previous one (from the same platform with
@@ -18,6 +18,7 @@ usage()
     echo "  (-l |-list )MACHINES  check platforms from this list"
     echo "                         [def=\"$MACHINES\"]"
     echo "  (-d |-day  )FIRSTDAY  select output from day=\"YYYYMMDD\""
+    echo "                         (argument of \"date -d\" is allowed)"
     echo "                         [def=\"$FIRSTDAY\"]"
     echo "  (-u |-upto )LASTDAY   until last day=\"YYYYMMDD\" (=selected period)"
     echo "                         [def=\"FIRSTDAY\"]"
@@ -101,6 +102,16 @@ for ac_option ; do
      esac
 
 done
+#-- test FIRSTDAY content ; interpret as "date -d" arg. if not YYYYMMDD
+ttt=`echo "y$FIRSTDAY" | sed 's/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/z/'`
+if test "x$ttt" != 'xyz' ; then
+   FIRSTDAY=`date -d "$FIRSTDAY" +%Y%m%d`
+fi
+ttt=`echo "y$FIRSTDAY" | sed 's/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/z/'`
+if test "x$ttt" != 'xyz' ; then
+  echo "Error: FIRSTDAY='$FIRSDAY' not recognized"
+  exit 2
+fi
 if test $LASTDAY = "30000000" ; then LASTDAY=$FIRSTDAY ; fi
 CMDLINE=$0
 for xx in "$@" ; do nw=`echo $xx | wc -w`
@@ -144,7 +155,7 @@ if test -d $INDIR ; then
   fi
 else
   echo "$INDIR is not a directory"
-  exit
+  exit 3
 fi
 
 #- a short summary of this checking :
@@ -375,4 +386,4 @@ if test "x$ADDRESS" != 'xnone' ; then
 fi
 echo ".. cat $OUTPSUM"
 cat $OUTPSUM
-
+exit 0
